### ISSUE TITLE
[Bug] Crash or Compatibility

### ISSUE THREAD

**Issue by VelvetRose252** [Traben-0/Entity_Model_Features#169]
**Describe the bug**
Hi I'm trying to fix my CITs not appearing in my 1.20.4 game. I tried installing all different 1.20.4 releases of Entity Model Features with the 1.20.4 Optifabric one at a time but Fabric keeps giving me the same error message over and over. What version of Entity Model would be compatible to Optifabric  1.14.3 or what Optifabric version would work with EMF?

**To Reproduce**
1. Download EMF 1.2.3 or 1.2.2 or 1.2.3 (I already have ETF)
2. Download Optifabric 
3. Place both files into the mods folder
4. Start Minecraft launcher. Run the Fabric loader for 1.20.4,
5. Run into error

**Expected behavior**
Supposed to start up Minecraft smoothly 

**Screenshots**
![image](https://github.com/Traben-0/Entity_Model_Features/assets/60297139/badf5583-6fd4-432f-870d-7747d379907f)

**Crashlog**
If applicable, add your crashlog or latest.log to help explain your problem.

**(please complete the following information):**
 - Minecraft Version: [e.g. 1.19.4]
 - EMF version: EMF 1.2.3,  1.2.2 , and 1.2.3
 - Does the issue persist with only EMF installed? I already EFT. Problem still persists
 - if applicable, provide your modlist or log
    My set up with Optifabric with Fabric loader, Fabric API, CIT resewn, EMF and EFT.

**Additional context**

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Entity Model Features' (entity_model_features) 1.2.3 with any version that is compatible with:
		 - optifabric 1.14.3
More details:
	 - Mod 'Entity Model Features' (entity_model_features) 1.2.3 is incompatible with any version of mod 'OptiFabric' (optifabric), but a matching version is present: 1.14.3!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by VelvetRose252** [comment]
Hi, thank you for the quick and helpful explanation, it explains a lot about why many of the things I done didn't work. If I'm hearing correctly, I either go with Fabulously Optimized and replace Optifine, or I replace Optifine with just CIT Resewn. I tried going with the Fabulously Optimized route and I see that it has a .mrpack extension. Do I just plop it right into the mods folder or should I double-click it to run it?

**Comment by VelvetRose252** [comment]
Sounds good, thank you so much !
